// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLoiBtS2jyxPZAdD3kUwhgcwNtdk8D1Y',
    appId: '1:658285594657:web:89a76a028e2ebd1908bb60',
    messagingSenderId: '658285594657',
    projectId: 'communications-app-86063',
    authDomain: 'communications-app-86063.firebaseapp.com',
    storageBucket: 'communications-app-86063.appspot.com',
    measurementId: 'G-E635TFP9ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbH86vPbYOlhitIlpWrfi5QZc606XRPTw',
    appId: '1:658285594657:android:30f3e7d18371c53308bb60',
    messagingSenderId: '658285594657',
    projectId: 'communications-app-86063',
    storageBucket: 'communications-app-86063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMxceYelcpIK0XnNc5QZkRkDShtykF80',
    appId: '1:658285594657:ios:3da0c5deee9339f908bb60',
    messagingSenderId: '658285594657',
    projectId: 'communications-app-86063',
    storageBucket: 'communications-app-86063.appspot.com',
    iosClientId: '658285594657-7ruc3c8amsbfk9gku9mpd85p8tt8rss1.apps.googleusercontent.com',
    iosBundleId: 'com.example.communications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkMxceYelcpIK0XnNc5QZkRkDShtykF80',
    appId: '1:658285594657:ios:3da0c5deee9339f908bb60',
    messagingSenderId: '658285594657',
    projectId: 'communications-app-86063',
    storageBucket: 'communications-app-86063.appspot.com',
    iosClientId: '658285594657-7ruc3c8amsbfk9gku9mpd85p8tt8rss1.apps.googleusercontent.com',
    iosBundleId: 'com.example.communications',
  );
}
